# Generated by Django 5.1.2 on 2024-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
